name: Build

on:
  push:
    branches: [ master ]
    paths: 
      - src/
      - GeneXus.DeploymentTargets.nuspec.template

jobs:
  build:
    env:
      NuGetRepository: http://nexus.genexus.com/repository/nuget-prereleases/
    # This will run on our very own servers
    runs-on: armado-virtual

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: Run the package script
      run: .\package.ps1

    - name: Push to Nuget Repository
      run: |
        Get-ChildItem .\*.nupkg -Recurse |
          ForEach-Object {
            dotnet nuget push $_.FullName --source $Env:NuGetRepository
        }
