name: Build

on:
  push:
    branches: [ master ]
    paths: 
      - .github/workflows/package.yml
      - src/
      - GeneXus.DeploymentTargets.nuspec

jobs:
  build:
    env:
      NuGetRepository: http://nexus.genexus.com/repository/nuget-hosted/

    runs-on: armado-virtual

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: Build NuGet package
      run: |
        $nuspec = ".\GeneXus.DeploymentTargets.nuspec"
        $xpath = "/package/metadata/version"
        $xml = Select-Xml $nuspec -XPath $xpath

        $packageVersion = $xml.Node.'#text'
        echo "::set-env name=NuGetPackageVersion::$packageVersion"

        $xpath = "/package/metadata/id"
        $xml = Select-Xml $nuspec -XPath $xpath

        $packageName = $xml.Node.'#text'
        echo "::set-env name=NuGetPackageName::$packageName"

        $packageFullName = $packageName + "." + $packageVersion
        echo "::set-env name=NuGetFullName::$packageFullName"
        
        Write-Host Packaging $packageName version $packageVersion ($packageFullName)

        nuget pack $nuspec 

    - name: Push to Nuget Repository
      run: dotnet nuget push $NuGetFullName.nupkg --source $Env:NuGetRepository

    - name: Checkout private action
      uses: actions/checkout@v2
      with:
          repository: genexuslabs/dispatch-build-result
          ref: releases/v2
          token: ${{ secrets.PAT }}
          path: .github/actions/dispatch-build-result
          
    - name: Dispatch build result
      uses: ./.github/actions/dispatch-build-result
      with:
        new-version: ${{ env.NuGetPackageVersion }}
        token: ${{ secrets.PAT }}
        committer: ${{ github.actor }}
        package-names: ${{ env.NuGetPackageName }}
