name: Build

on:
  push:
    branches: [ master ]
    paths: 
      - src/
      - GeneXus.DeploymentTargets.nuspec

jobs:
  build:
    env:
      NuGetRepository: http://nexus.genexus.com/repository/nuget-prereleases/

    runs-on: armado-virtual

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: Build NuGet package
      run: |
        $nuspec = ".\GeneXus.DeploymentTargets.nuspec"
        $xpath = "/package/metadata/version"

        $xml = Select-Xml $nuspec -XPath $xpath

        $packageVersion = $xml.Node.'#text'
        echo "::set-env name=NuGetPackageVersion::$packageVersion"

        Write-Host Packaging GeneXus.DeploymentTargets version $packageVersion

        nuget pack $nuspec 

    - name: Push to Nuget Repository
      run: dotnet nuget push GeneXus.DeploymentTargets.$Env:NuGetPackageVersion.nupkg --source $Env:NuGetRepository

    - name: Checkout private action
      uses: actions/checkout@v2
      with:
          repository: genexuslabs/dispatch-build-result
          ref: v1.1
          token: ${{ secrets.PAT }}
          path: .github/actions/dispatch-build-result
          
    - name: Dispatch build result
      uses: ./.github/actions/dispatch-build-result
      with:
        new-version: ${{ env.NuGetPackageVersion }}
        token: ${{ secrets.PAT }}