name: Build

on:
  push:
    branches: [ master ]
    paths: 
      - .github/workflows/package.yml
      - src/
      - GeneXus.DeploymentTargets.nuspec

jobs:
  build:
    env:
      NuGetRepository: ${{ secrets.NEXUS_NUGET_RELEASES }}
      Nuspec: GeneXus.DeploymentTargets.nuspec

    runs-on: armado-virtual

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1

    - name: Clean previous build #Because self-hosted runners are not cleaned automatically
      run: |
        Get-ChildItem *.nupkg -ErrorAction SilentlyContinue |
          ForEach-Object {
           rm $_.FullName
        }

    - name: Build NuGet package
      run: |
        #Generate a new package version reading the current commit number
        $CommitNumber = git rev-list --no-merges --count HEAD
        $PackageVersion = dotnet msbuild Directory.Build.props /t:GetVersion /p:CommitNumber=$CommitNumber
        "$PackageVersion" -match "(?<=FileVersion:)(.*)"
        $PackageVersion = $Matches[0].Trim()

        if ([string]::IsNullOrEmpty($packageVersion)) {
          throw "Cannot create new package because the current package version is empty"
        }

        nuget pack $Env:Nuspec -Version "$PackageVersion"

        echo "::set-env name=NuGetPackageVersion::$packageVersion"

    - name: Push to Nuget Repository
      run: | 
        $nupkg = (Get-ChildItem *.nupkg).Name
        dotnet nuget push $nupkg --source $Env:NuGetRepository

    - name: Checkout private action
      uses: actions/checkout@v2
      with:
          repository: genexuslabs/dispatch-build-result
          ref: releases/v2
          token: ${{ secrets.PAT }}
          path: .github/actions/dispatch-build-result
          
    - name: Prepare build result
      if: github.repository_owner == 'GeneXusLabs'
      run: |
        Import-Module ./.github/actions/dispatch-build-result/utils/CSProjUtils -Force
        $packageNames = Gather-Nupkg-Names (Get-Location).Path $false
        
        if ([string]::IsNullOrEmpty($packageNames)) {
          throw "Cannot found package to integrate"
        }

        echo "::set-env name=DispatchPackageNames::$packageNames"

    - name: Dispatch build result
      uses: ./.github/actions/dispatch-build-result
      with:
        new-version: ${{ env.NuGetPackageVersion }}
        token: ${{ secrets.PAT }}
        committer: ${{ github.actor }}
        package-names: ${{ env.DispatchPackageNames }}
